apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sahi-guesser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sjc.vultrcr.com/sahiguessercs/sahi-guesser-frontend:latest
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: DEPLOYMENT_VERSION
              value: "12"
          ports:
            - containerPort: 9999
