apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sahi-guesser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
    strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1 # Number of pods that can be unavailable during the update
      maxSurge: 1
      containers:
        - name: frontend
          image: sjc.vultrcr.com/sahiguessercs/sahi-guesser-frontend:latest
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: DEPLOYMENT_VERSION
              value: "12"
          ports:
            - containerPort: 9999
          readinessProbe:
            httpGet:
              path: /
              port: 9999
            initialDelaySeconds: 3
            periodSeconds: 5
